ldap_server: "192.168.56.10"
domain: "corp.local"
bind_dn: "CN=Administrator,CN=Users,DC=corp,DC=local"
password: "P@ssw0rd123"
target_dn: "CN=User1,CN=Users,DC=corp,DC=local"
sid_to_inject: "S-1-5-21-1111111111-2222222222-3333333333-500"
