- ldap_server: "dc01.corp.local"
  username: "admin"
  password: "P@ssw0rd!"
  domain: "corp.local"
  target_dn: "CN=User1,CN=Users,DC=corp,DC=local"
  sid_to_inject: "S-1-5-21-999999999-999999999-999999999-500"
  attacker_sid: "S-1-5-21-999999999-999999999-999999999-1105"
  acl_ace: "FAKE_ACE_DATA"
  sid_injection: true
  adminsdholder_abuse: true
  acl_backdoor: true
