# List of target IPs or hostnames to test
targets:
  - "192.168.1.10"
  - "test.example.com"

# Modules to load from src/modules/
modules:
  - name: "cve_2021_1234"
    params:
      exploit_mode: "safe"
      timeout: 5
  - name: "cve_2020_5678"
    params:
      payload: "reverse_shell"
      lhost: "192.168.1.100"
      lport: 4444
